### PR TITLE
Migrate documentation to Great Docs

### PR DESCRIPTION
**Pull request by uriahf**
## What changed

- migrate the documentation configuration from quartodoc/Quarto to Great Docs
- move the Getting Started guide into `user_guide/`
- organize the documented public API into performance-data, discrimination, calibration, and utility groups
- include the existing classification and time-to-event APIs
- add a dedicated `docs` dependency group so package support remains Python >=3.9 while docs build on Python 3.11
- separate package CI from documentation publishing
- publish production documentation to the existing `gh-pages` root
- deploy pull-request previews under `pr-preview/pr-<number>/`
- preserve PR preview directories during production documentation deployments
- style Great Docs with the rtichoke-blog palette and typography, including its bundled heading font
- remove obsolete quartodoc documentation infrastructure after migrating its useful content

## Scope

This PR only migrates documentation infrastructure and content. It does not implement or redesign `create_summary_report()`; its source remains unchanged from `main`.

## Validation

- package tests pass
- Ruff checks pass
- the full Great Docs build passes
- all 21 configured API pages render, including 8 time-to-event APIs
- all Python examples from `rtichoke-blog` render successfully against this branch
- PR preview deployment passes and serves the custom stylesheet and bundled font
- production documentation remains configured for https://uriahf.github.io/rtichoke_python/
- PR preview: https://uriahf.github.io/rtichoke_python/pr-preview/pr-282/

### CODE REVIEW

**Review by uriahf — COMMENTED** [review]
Looks good
